Refactor bootstrap script for Zunit test environment

diff --git a/tests/_support/bootstrap b/tests/_support/bootstrap
--- a/tests/_support/bootstrap
+++ b/tests/_support/bootstrap
@@ -10,30 +10,30 @@ function warn() { print -P "%F{yellow}[WARN]%f: ${1}"; }
 # ]]]
 
 # Create Zunit test environment [[[
+
 GIT_REPO=$(git rev-parse --show-toplevel)
 
-local _mktemp_cmd='mktemp'
-(( ${+commands[gmktemp]} )) && {
-  _mktemp_cmd='gmktemp'
-}
-
+_mktemp_cmd='mktemp'
+if (( ${+commands[gmktemp]} )); then
+    _mktemp_cmd='gmktemp'
+fi
 TMP_ZUNIT=$(${_mktemp_cmd} --directory --tmpdir="${GIT_REPO}/tests/_support")
-[[ -d ${TMP_ZUNIT} ]] || {
-  error "zunit temp dir not found"
-}
+if [[ ! -d ${TMP_ZUNIT} ]]; then
+    error "zunit temp dir not found"
+    exit 1
+fi
 
 typeset -gx zi_test_dir="${TMP_ZUNIT}"
-typeset -gxAUH ZINIT
+typeset -gxAUH ZINIT=()
 ZINIT+=(
-  BIN_DIR         ${zi_test_dir}/zinit.git
-  COMPLETIONS_DIR ${zi_test_dir}/completions SNIPPETS_DIR ${zi_test_dir}/snippets
-  HOME_DIR        ${zi_test_dir}             PLUGINS_DIR  ${zi_test_dir}/plugins
-  ZCOMPDUMP_PATH  ${zi_test_dir}/zcompdump   ZPFX         ${zi_test_dir}/polaris
-  POLARIS         ${zi_test_dir}/polaris
+  BIN_DIR         "${zi_test_dir}/zinit.git"
+  COMPLETIONS_DIR "${zi_test_dir}/completions" SNIPPETS_DIR "${zi_test_dir}/snippets"
+  HOME_DIR        "${zi_test_dir}"             PLUGINS_DIR  "${zi_test_dir}/plugins"
+  ZCOMPDUMP_PATH  "${zi_test_dir}/zcompdump"   ZPFX         "${zi_test_dir}/polaris"
+  POLARIS         "${zi_test_dir}/polaris"
 )
-
 typeset -gxH ZPFX=
-ZPFX="$zi_test_dir"/polaris
+ZPFX="${zi_test_dir}/polaris"
 
 command git diff > ${ZINIT[HOME_DIR]}/unstaged.diff
 # info 'creating test env'
@@ -45,22 +45,20 @@ git clone \
     --reference "${GIT_REPO}" \
     file://${GIT_REPO:A} \
     "${ZINIT[BIN_DIR]}" >/dev/null
+if (( $? != 0 )); then
+    error "Unable to copy ${GIT_REPO} to ${TMP_ZUNIT}" >&2
+    exit 1
+fi
 
-(( $? == 0 )) && {
-  error "Unable to copy ${GIT_REPO} to ${TMP_ZUNIT}" >&2
-  exit 1
-}
+if [[ -s $ZINIT[HOME_DIR]/unstaged.diff ]]; then
+    (
+        git -C "${ZINIT[BIN_DIR]}" apply "${ZINIT[HOME_DIR]}/unstaged.diff" && \
+            chmod g-rwX "${ZINIT[HOME_DIR]}" && \
+            zcompile "${ZINIT[BIN_DIR]}/zinit.zsh" >/dev/null
+    ) >/dev/null
+fi
+(( $? != 0 )) && { error "Unable to copy ${GIT_REPO} to ${TMP_ZUNIT}" >&2; exit 1 }
 
-[[ -s $ZINIT[HOME_DIR]/unstaged.diff ]] && {
-  git -C $ZINIT[BIN_DIR] apply $ZINIT[HOME_DIR]/unstaged.diff \
-    && chmod g-rwX "${ZINIT[HOME_DIR]}" \
-    && zcompile "${ZINIT[BIN_DIR]}/zinit.zsh" >/dev/null
-} >/dev/null
-
-(( $? == 0 )) || {
-  error "Unable to copy ${GIT_REPO} to ${TMP_ZUNIT}" >&2
-  exit 1 
-}
 
 hash -f
 builtin hash -d zinit=${zi_test_dir}
